version: 2.1
jobs:
  compile:
   docker:
      - image: bionic
   steps:
      - run:
          command: |
            dpkg-reconfigure --frontend noninteractive tzdata
            curl https://raw.githubusercontent.com/AnGgIt86/llvm-build/main/llvm-tc_build.sh -o llvm-tc_build.sh
            source ./llvm-tc_build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile 
      
