version: 2.1
jobs:
  compile:
   docker:
      - image: xyzuan/xdocker:latest
   environment:
      GIT_EMAIL: jarbull86@gmail.com
      GIT_NAME: AnGgIt86
      VERSION: rev1.5_template
   steps:
      - run:
          command: |
            dpkg-reconfigure --frontend noninteractive tzdata
            curl https://raw.githubusercontent.com/AnGgIt86/llvm-build/main/llvm-tc_build.sh -o llvm-tc_build.sh
            source ./llvm-tc_build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile 
      
