version: 2.1
jobs:
  compile:
   docker:
      - image: xyzuan/xdocker:latest
   environment:
      GIT_EMAIL: jarbull86@gmail.com
      GIT_NAME: AnGgIt86
      VERSION: rev1.5_template
   steps:
      - run:
          command: |
           bash llvm-tc_build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile 
      
